# Generated by Django 4.1.4 on 2022-12-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_class_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rooster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.class'),
        ),
    ]
